[env]
TERM = "screen-256color"

[general]
import = [
	#	"~/.config/alacritty/themes/themes/aura.toml"
	#"~/.config/alacritty/themes/themes/blood_moon.toml"
		"~/.config/alacritty/themes/themes/github_dark_default.toml"
	#	"~/.config/alacritty/themes/themes/github_light.toml"
]

[colors]
# primary.background = '#141415'

[scrolling]
multiplier = 255

[selection]
save_to_clipboard = true

[font]
normal.family = "UbuntuMono Nerd Font"
#normal.style = "Bold"
size = 16

[window]
# startup_mode = "Fullscreen"
dimensions.columns = 95
dimensions.lines = 36

[cursor]
style.blinking = "Always"
blink_timeout = 0

[terminal]
shell.program = "/bin/fish"
shell.args = [ "-c", "/usr/bin/tmux"]

[keyboard]
bindings = [
	{ key = 'F11', action = "ToggleFullScreen" },
	{ key = 'F12', action = "ToggleViMode" },
	{ key = 'Escape', mode = 'Vi', action = "ToggleViMode" },
]
